# Generated by Django 5.2.7 on 2025-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancemetric",
            name="mae",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="mse",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="r2_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="rmse",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
