# Generated by Django 5.2.7 on 2025-11-01 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit Tests"),
                            ("integration", "Integration Tests"),
                            ("all", "All Tests"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("passed", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("duration", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_case", models.CharField(max_length=255)),
                ("test_method", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                ("duration", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "test_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="dbtest.testrun",
                    ),
                ),
            ],
            options={
                "ordering": ["test_case", "test_method"],
            },
        ),
    ]
